workflows:
  my-workflow:
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Tests
        script: npm test
      # - name: Build ipa for distribution
      #   script: xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme $XCODE_SCHEME
      - name: Build Android app
        script: cd android && ./gradlew assembleRelease
